version: '3'

services:
    #app
    app:
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      env_file:
        - .env
      ports:
        - ${PORT}:${PORT}
      networks:
        - backend

networks:
  backend:
    external: true